ecognome/druids/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = [

    # GT economia
    ## Cuotas
    url(r'^gt-economia/cuotas/mantenimiento/crear/',
        views.CuotaMantenimientoCreateView.as_view(),
        name="crear-mantenimiento"
        ),
    url(r'^gt-economia/cuotas/mantenimiento/',
        views.CuotaMantenimientoListView.as_view(),
        name="lista-mantenimiento"
        ),
    url(r'^gt-economia/cuotas/piso/crear/',
        views.CuotaPisoCreateView.as_view(),
        name="crear-cuota-piso"
        ),
    url(r'^gt-economia/cuotas/piso/',
        views.CuotaPisoListView.as_view(),
        name="lista-cuotas-piso"
        ),

    ## Espacios
    url(r'^gt-economia/espacios/pisos/crear/',
        views.PisoCreateView.as_view(),
        name="crear-piso"
        ),
    url(r'^gt-economia/espacios/pisos/(?P<pk>\d+)/',
        views.PisoUpdateView.as_view(),
        name="editar-piso"
        ),
    url(r'^gt-economia/espacios/pisos/',
        views.PisoListView.as_view(),
        name="lista-pisos"
        ),
    url(r'^gt-economia/espacios/trasteros/crear/',
        views.TrasteroCreateView.as_view(),
        name="crear-trastero"
        ),
    url(r'^gt-economia/espacios/trasteros/(?P<pk>\d+)/',
        views.TrasteroUpdateView.as_view(),
        name="editar-trastero"
        ),
    url(r'^gt-economia/espacios/trasteros/',
        views.TrasteroListView.as_view(),
        name="lista-trasteros"
        ),

    
    ## Registros
    url(r'^gt-economia/registros/metalico/crear/',
        views.MetalicoCreateView.as_view(),
        name="crear-metalico"
        ),
    url(r'^gt-economia/registros/metalico/',
        views.MetalicoListView.as_view(),
        name="lista-metalicos"
        ),
    url(r'^gt-economia/registros/banco/crear/',
        views.BancoCreateView.as_view(),
        name="crear-banco"
        ),
    url(r'^gt-economia/registros/banco/',
        views.BancoListView.as_view(),
        name="lista-bancos"
        ),
    url(r'^gt-economia/registros/electronico/crear/',
        views.PaypalCreateView.as_view(),
        name="crear-paypal"
        ),
    url(r'^gt-economia/registros/electronico/',
        views.PaypalListView.as_view(),
        name="lista-paypals"
        ),

    ## Proyectos
    url(r'^gt-economia/proyectos/crear/',
        views.ProyectoProductivoCreateView.as_view(),
        name="crear-proyecto"
        ),
    url(r'^gt-economia/proyectos/(?P<pk>\d+)/',
        views.ProyectoProductivoUpdateView.as_view(),
        name="editar-proyecto"
        ),
    url(r'^gt-economia/proyectos/',
        views.ProyectoProductivoListView.as_view(),
        name="lista-proyectos"
        ),

    ## Personas
    url(r'^gt-economia/personas/habitantes/crear/',
        views.HabitanteCreateView.as_view(),
        name="crear-habitante"
        ),
    url(r'^gt-economia/personas/habitantes/(?P<pk>\d+)/',
        views.HabitanteUpdateView.as_view(),
        name="editar-habitante"
        ),
    url(r'^gt-economia/personas/habitantes/',
        views.HabitanteListView.as_view(),
        name="lista-habitantes"
        ),
    url(r'^gt-economia/personas/invitadas/crear/',
        views.InvitadaCreateView.as_view(),
        name="crear-invitada"
        ),
    url(r'^gt-economia/personas/invitadas/(?P<pk>\d+)/',
        views.InvitadaUpdateView.as_view(),
        name="editar-invitada"
        ),
    url(r'^gt-economia/personas/invitadas/',
        views.InvitadaListView.as_view(),
        name="lista-invitadas"
        ),
    url(r'^gt-economia/personas/huespedes/crear/',
        views.HuespedCreateView.as_view(),
        name="crear-huesped"
        ),
    url(r'^gt-economia/personas/huespedes/(?P<pk>\d+)/',
        views.HuespedUpdateView.as_view(),
        name="editar-huesped"
        ),
    url(r'^gt-economia/personas/huespedes/',
        views.HuespedListView.as_view(),
        name="lista-huespedes"
        ),

    ## Pactos
    url(r'^gt-economia/pactos/habitantepiso/crear/',
        views.HabitantePisoCreateView.as_view(),
        name="crear-habitantepiso"
        ),
    url(r'^gt-economia/pactos/habitantepiso/(?P<pk>\d+)/',
        views.HabitantePisoUpdateView.as_view(),
        name="editar-habitantepiso"
        ),
    url(r'^gt-economia/pactos/habitantepiso/',
        views.HabitantePisoListView.as_view(),
        name="lista-habitantepiso"
        ),
    url(r'^gt-economia/pactos/personatrastero/crear/',
        views.PersonaTrasteroCreateView.as_view(),
        name="crear-personatrastero"
        ),
    url(r'^gt-economia/pactos/personatrastero/(?P<pk>\d+)/',
        views.PersonaTrasteroUpdateView.as_view(),
        name="editar-personatrastero"
        ),
    url(r'^gt-economia/pactos/personatrastero/',
        views.PersonaTrasteroListView.as_view(),
        name="lista-personatrastero"
        ),

    ## Movimientos
    url(r'^gt-economia/movimientos/salidas/crear/',
        views.insertar_salidas,
        name="crear-salida"
        ),
    url(r'^gt-economia/movimientos/entradas/otras/crear/',
        views.insertar_entradas_otras,
        name="crear-otras-entradas"
        ),
    url(r'^gt-economia/movimientos/entradas/alquileres/crear/',
        views.insertar_entradas_alquileres,
        name="crear-alquileres-entradas"
        ),
    url(r'^gt-economia/movimientos/entradas/proyectos/crear/',
        views.insertar_entradas_proyectos,
        name="crear-proyectos-entradas"
        ),

    ## Balances
    url(r'^gt-economia/balances/crear/',
        views.BalanceCreateView.as_view(),
        name="crear-balance"
        ),
    url(r'^gt-economia/balances/(?P<pk>\d+)/',
        views.BalanceDetailView.as_view(),
        name="ver-balance"
        ),
    url(r'^gt-economia/balances/',
        views.BalanceListView.as_view(),
        name="lista-balances"
        ),

    ## Dashboard
    url(r'^gt-economia/', views.gt_dashboard, name='gt-dashboard'),

    # Public dashboard
    ## API
    url(r'^api/cloud-data/', views.get_dashboard_data, name='api-cloud-data'),
    url(r'^api/entradas-pie/', views.get_entradas_pie_chart_data, name='api-entradas-pie'),
    url(r'^api/salidas-pie/', views.get_salidas_pie_chart_data, name='api-salidas-pie'),
    url(r'^api/balance-line-graph/', views.get_balance_general_data, name='api-balance-line-graph'),

    ## Situaciones personales
    url(r'^situaciones-personales/(?P<habitante_id>\d+)/', views.situaciones_personales, name='situaciones-personales'),
    url(r'^situaciones-personales/', views.situaciones_personales, name='situaciones-personales'),

    ## Balance general
    url(r'^balance-general/', views.balance_general, name='balance-general'),
    
    ## Index
    url(r'^$', views.index, name='index'),

]

ecognome/ecognome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Admin related URLs
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    # Frontend related URLs
    url(r'^foundation/', include('foundation.urls')),
    # Login related URLs
    url(r'^accounts/', include([
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
        # Password related URLs
        url(r'^password/', include([
            url(r'^change/$', auth_views.password_change, name='password_change'),
            url(r'^change/done/$', auth_views.password_change_done, name='password_change_done'),
            ])),
        ])),
    # Druids app
    url(r'^', include('druids.urls', namespace='druids')),
]

ecognome/druids/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.decorators import method_decorator
from django.forms.models import modelform_factory, modelformset_factory
from django.forms.widgets import Select
from django.http import JsonResponse

from .forms import SelectHabitanteForm
from .models import CuotaMantenimiento, CuotaPiso, \
    Piso, Trastero, \
    Metalico, Banco, PayPal, Registro, \
    ProyectoProductivo, \
    Habitante, Invitada, Huesped, \
    HabitantePiso, PersonaTrastero, \
    Salida, \
    EntradaMantenimiento, EntradaPiso, EntradaAlquiler, \
    EntradaDonativo, EntradaBeneficiosEvento, OtraEntrada, \
    EntradaEspacioProyectoProductivo, EntradaBeneficioProyectoProductivo, \
    EntradaAlquilerTrastero, EntradaTransferencia, Entrada, \
    Balance

from datetime import datetime, timedelta


def index(request):
    """
    Index dahsboard for druids app.
    """
    return render(
        request,
        'druids/index.html'
        )


def situaciones_personales(request, habitante_id=None):
    """
    This view renders a form that is used to update the content
    of the view. If `habitante_id` is None only the form will be rendered.
    Else, all the relevant information about specific `Habitante` will be rendered.
    """

    title = "Situaciones Personales"

    habitante = None
    estado_pactos_de_piso = None
    estado_pactos_trastero = None
    if request.method == 'POST':
        form = SelectHabitanteForm(request.POST)
        if form.is_valid():
            selected = form.cleaned_data['habitante']
            habitante_id = selected.id
            return redirect('druids:situaciones-personales', habitante_id=habitante_id)

    else:
         form = SelectHabitanteForm()
         if habitante_id is not None:
             habitante = get_object_or_404(Habitante, id=habitante_id)
             if habitante.tiene_pacto_trastero:
                 estado_pactos_trastero = habitante.estado_pactos_trastero
             if habitante.tiene_pacto_de_piso:
                 estado_pactos_de_piso = habitante.estado_pactos_de_piso

    return render(request,
                  'druids/situaciones_personales.html',
                  {
                      'title': title,
                      'habitante': habitante,
                      'form': form,
                      'estado_pactos_trastero': estado_pactos_trastero,
                      'estado_pactos_de_piso': estado_pactos_de_piso,
                  }
              )


def balance_general(request):
    """
    Main balance in accounting view.
    """
    title = "Balance general"

    total = str(sum([entrada.importe for entrada in Entrada.objects.all()]) - sum([salida.importe for salida in Salida.objects.all()]))

    return render(request,
                  'druids/balance_general.html',
                  {
                      'title': title,
                      'total': total,
                  }
              )

             
@login_required
def gt_dashboard(request):
    """
    Dashboard for GT Economía
    """
    return render(
        request,
        'druids/gt-dashboard.html'
        )


class CuotaMantenimientoCreateView(SuccessMessageMixin, CreateView):
    """
    Create View for CuotaMantenimiento
    model.
    """
    model = CuotaMantenimiento
    template_name = 'druids/cuotas/crear_mantenimiento.html'
    form_class = modelform_factory(CuotaMantenimiento,
                                   fields=['descripcion', 'tipo', 'importe']
                               )
    success_url = '/gt-economia/'
    success_message = 'La cuota de mantenimiento se ha creado correctamente.'

    title = 'Crear cuota de mantenimiento'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CuotaMantenimientoCreateView, self).dispatch(*args, **kwargs)


class CuotaMantenimientoListView(ListView):
    """
    List View for CuotaMantenimiento model.
    """
    context_object_name = 'cuotas'
    queryset = CuotaMantenimiento.objects.all().order_by('tipo')
    template_name = "druids/cuotas/lista_mantenimiento.html"
    title = 'Lista de cuotas de mantenimiento'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CuotaMantenimientoListView, self).dispatch(*args, **kwargs)


class CuotaPisoCreateView(SuccessMessageMixin, CreateView):
    """
    Create View for CuotaPiso
    model.
    """
    model = CuotaPiso
    template_name = 'druids/cuotas/crear_mantenimiento.html'
    form_class = modelform_factory(CuotaPiso,
                                   fields=['importe', 'descripcion']
                               )
    success_url = '/gt-economia/'
    success_message = 'La cuota de piso se ha creado correctamente.'

    title = 'Crear cuota de piso'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CuotaPisoCreateView, self).dispatch(*args, **kwargs)


class CuotaPisoListView(ListView):
    """
    List View for CuotaMantenimiento model.
    """
    context_object_name = 'cuotas'
    queryset = CuotaPiso.objects.all().order_by('importe')
    template_name = "druids/cuotas/lista_cuotas_piso.html"
    title = 'Lista de cuotas de piso'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CuotaPisoListView, self).dispatch(*args, **kwargs)


class PisoCreateView(SuccessMessageMixin, CreateView):
    """
    Create View for Piso model.
    """
    model = Piso
    template_name = "druids/espacios/crear-piso.html"
    form_class = modelform_factory(Piso,
                                   fields=['nombre', 'valor_total', 'cuota_piso']
                               )
    success_url = '/gt-economia/'
    success_message = 'El piso se ha creado correctamente.'

    title = 'Crear piso'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PisoCreateView, self).dispatch(*args, **kwargs)


class PisoListView(ListView):
    """
    List View for Piso model.
    """
    context_object_name = 'pisos'
    queryset = Piso.objects.all().order_by('nombre')
    template_name = "druids/espacios/lista-pisos.html"
    title = "Lista de pisos"

    edit_url = "druids:editar-piso"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PisoListView, self).dispatch(*args, **kwargs)


class PisoUpdateView(SuccessMessageMixin, UpdateView):
    """
    Update View for Piso model.
    """
    model = Piso
    template_name = "druids/espacios/crear-piso.html"
    fields = ['nombre', 'valor_total', 'cuota_piso']
    
    title = "Modificar piso"

    success_url = "/gt-economia/"
    success_message = "El piso se ha modificado correctamente."

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PisoUpdateView, self).dispatch(*args, **kwargs)


class TrasteroCreateView(SuccessMessageMixin, CreateView):
    """
    Create View for Trastero model.
    """
    model = Trastero
    template_name = "druids/espacios/crear-trastero.html"
    form_class = modelform_factory(Trastero,
                                   fields=['nombre', 'cuota_trastero']
                               )
    success_url = '/gt-economia/'
    success_message = 'El trastero se ha creado correctamente.'

    title = 'Crear trastero'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TrasteroCreateView, self).dispatch(*args, **kwargs)


class TrasteroListView(ListView):
    """
    List View for Trastero model.
    """
    context_object_name = 'trasteros'
    queryset = Trastero.objects.all().order_by('nombre')
    template_name = "druids/espacios/lista-trasteros.html"
    title = "Lista de trasteros"

    edit_url = "druids:editar-trastero"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TrasteroListView, self).dispatch(*args, **kwargs)


class TrasteroUpdateView(SuccessMessageMixin, UpdateView):
    """
    Update View for Trastero model.
    """
    model = Trastero
    template_name = "druids/espacios/crear-trastero.html"
    fields = ['nombre', 'cuota_trastero']
    
    title = "Modificar trastero"

    success_url = "/gt-economia/"
    success_message = "El trastero se ha modificado correctamente."

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TrasteroUpdateView, self).dispatch(*args, **kwargs)


class MetalicoCreateView(SuccessMessageMixin, CreateView):
    """
    Create View for Metalico model.
    """
    model = Metalico
    template_name = "druids/registros/crear_registro.html"
    form_class = modelform_factory(Metalico,
                                   fields=["nombre"]
                               )

    title = "Crear registro de metálico"
    
    success_url = "/gt-economia/"
    success_message = "El registro de metálico se ha creado correctamente."

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MetalicoCreateView, self).dispatch(*args, **kwargs)
    

class MetalicoListView(ListView):
    """
    List View for Metalico model.
    """
    context_object_name = "registros"
    queryset = Metalico.objects.all().order_by('nombre')
    template_name = "druids/registros/lista-registros.html"
    title = "Lista de registros de metálico"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):

ecognome/druids/templates/druids/gt-dashboard.html
{% extends "druids.html" %}

{% block title %}Dashboard GT Economía{% endblock title %}

{% block content %}
<div class="row">
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-dollar-bill size-72"></i> Movimientos de guita</legend>
      <ul class="radius button-group even-4">
	<li>
	  <a href="#" class="disabled info button small">Entradas: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-alquileres-entradas' %}" class="button small">
	    <i class="fi-plus size-36"></i> Alquil.
	  </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-proyectos-entradas' %}" class="button small">
	    <i class="fi-plus size-36"></i> Proy.
	  </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-otras-entradas' %}" class="button small">
	    <i class="fi-plus size-36"></i> Otras
	  </a>
	</li>
      </ul>
      <ul class="radius button-group even-2">
	<li>
	  <a href="#" class="disabled info button">Salidas:</a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-salida' %}" class="button">
	    <i class="fi-plus size-36"></i> Todas
	  </a>
	</li>
      </ul>
    </fieldset>
  </div>
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-home size-72"></i> Espacios</legend>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled info button">Pisos: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-piso' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-pisos' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled info button">Trasteros: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-trastero' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-trasteros' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul
    </fieldset>
  </div>
</div>
<div class="row">
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-clipboard-notes"></i> Cuotas</legend>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled info button">Pisos: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-cuota-piso' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-cuotas-piso' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled info button">Mantenimiento: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-mantenimiento' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-mantenimiento' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
    </fieldset>
  </div>
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-link size-72"></i> Pactos de reciprocidad</legend>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled button info">Hab. Piso: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-habitantepiso' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-habitantepiso' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled button info">Per. Trast.: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-personatrastero' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-personatrastero' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
    </fieldset>
  </div>
</div>
<div class="row">
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-social-myspace size-72"></i> Calafouenses</legend>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled info button">Huespedes: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-huesped' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-huespedes' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled info button">Invitadas: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-invitada' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-invitadas' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled info button">Habitantes: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-habitante' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-habitantes' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>      
    </fieldset>
  </div>
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-list-bullet"></i> Registros</legend>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled button info">Metálico: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-metalico' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-metalicos' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled button info">Bancario: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-banco' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-bancos' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
      <ul class="radius button-group even-3">
	<li>
	  <a href="#" class="disabled button info">Electrónico: </a>
	</li>
	<li>
	  <a href="{% url 'druids:crear-paypal' %}" class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-paypals' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
    </fieldset>
  </div>+
</div>
<div class="row">
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-social-steam"></i> Proyectos Productivos</legend>
      <ul class="radius button-group even-2">
	<li>
	  <a href="{% url 'druids:crear-proyecto' %} " class="button"><i class="fi-plus size-36"></i> Crear</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-proyectos' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
    </fieldset>
  </div>
  <div class="medium-6 columns">
    <fieldset>
      <legend><i class="fi-ticket size-72"></i> Balances</legend>
      <ul class="radius button-group even-2">
	<li>
	  <a href="{% url 'druids:crear-balance' %}" class="button"><i class="fi-plus size-36"></i>  Generar</a>
	</li>
	<li>
	  <a href="{% url 'druids:lista-balances' %}" class="button"><i class="fi-align-center size-36"></i> Listar</a>
	</li>
      </ul>
    </fieldset>
  </div>
</div>
{% endblock content %}